'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../revdesk/core.js'),D=require('../revdesk/data.js');
const NOW='2026-10-07T15:00:00.000Z';
function fixture(){const w=C.workspace();w.settings.timeZone='America/New_York';const d=C.deal({name:'Test Customer',business:'Test Business',entity:'single'},NOW);d.permission=true;d.facts={need:'Help with planning',impact:'More time for clients',timing:'Before next month',decision:'I decide',fit:'This is the help I need',criterion:'Terms are clear'};d.decisionType='solo';d.coverage.planning='gap';d.coverage.filing='gap';d.coverage.books='gap';w.deals.push(d);w.activeId=d.id;return{w,d};}
function quote(d,monthly=false){C.saveQuote(d,{id:'q-test',lines:[{productId:'bundle',name:'Test bundle',services:['planning','filing','books'],amount:monthly?19900:203800,billing:monthly?'monthly':'annual',months:12}],scope:'Test scope',terms:'Test verified terms',source:'Test order',verified:true,verifiedAt:NOW,expiresAt:'2026-10-14T15:00:00Z'},NOW);}
function authorized(monthly=false){const f=fixture();quote(f.d,monthly);C.accept(f.d,NOW);C.authorize(f.d,NOW);return f;}
function paid(monthly=false){const f=authorized(monthly);const p=C.recordPayment(f.w,f.d,{amount:monthly?19900:203800,reference:'TX-1',confirmed:true},NOW);return{...f,p};}
test('a blank customer has no recommendation and unknown coverage is not a gap',()=>{const w=C.workspace(),d=C.deal();assert.equal(C.recommendation(d,D.catalog),null);assert.deepEqual(C.needs(d),[]);assert.equal(C.action(w,d,D.catalog).kind,'permission');});
test('partially unknown coverage blocks recommendation even when a need is present',()=>{const{d}=fixture();d.coverage.books='unknown';assert.equal(C.recommendation(d,D.catalog),null);});
test('recommendation excludes all covered services and selects only confirmed gaps',()=>{const{d}=fixture();d.coverage.filing='covered';d.coverage.books='covered';assert.equal(C.recommendation(d,D.catalog).id,'planning');d.coverage.planning='covered';assert.equal(C.recommendation(d,D.catalog),null);});
test('external coverage is treated as covered and a complete gap picks a fitting bundle',()=>{const{d}=fixture();assert.equal(C.recommendation(d,D.catalog).id,'bundle');d.coverage.books='covered';d.coverageNotes.books='Outside bookkeeper';assert.equal(C.recommendation(d,D.catalog).id,'dify');});
test('an unverified or expired quote cannot be accepted',()=>{const{d}=fixture();quote(d);d.quote.verified=false;assert.throws(()=>C.accept(d,NOW),/Verify/);d.quote.verified=true;assert.throws(()=>C.accept(d,'2026-10-15T15:00:00Z'),/Verify/);});
test('covered services cannot be sold through an arbitrary quote',()=>{const{d}=fixture();d.coverage.books='covered';assert.throws(()=>quote(d),/confirmed gap/);});
test('a newly covered service invalidates a previously fitting recommendation',()=>{const{d}=fixture();quote(d);d.coverage.books='covered';assert.throws(()=>C.accept(d,NOW),/Coverage changed/);});
test('a shared decision without approval blocks agreement',()=>{const{d}=fixture();quote(d);d.decisionType='shared';assert.throws(()=>C.accept(d,NOW),/necessary people/);d.decisionReady=true;C.accept(d,NOW);assert.equal(d.acceptedAt,NOW);});
test('unresolved objections block agreement',()=>{const{d}=fixture();quote(d);d.objection={category:'cost',quote:'Too much',resolved:false};assert.throws(()=>C.accept(d,NOW),/open concern/);});
test('recommendation, agreement, and authorization contribute zero paid revenue',()=>{const{w,d}=authorized();assert.equal(C.status(w,d),'Authorized');assert.equal(C.netPaid(w,d.id),0);assert.equal(C.metrics(w).newPaidDeals,0);assert.equal(C.metrics(w).cash,0);});
test('removing an unaccepted recommendation changes no revenue',()=>{const{w,d}=fixture();quote(d);d.quote=null;assert.equal(C.metrics(w).cash,0);assert.equal(C.metrics(w).newPaidDeals,0);});
test('payment requires authorization and a successful transaction confirmation',()=>{const{w,d}=fixture();assert.throws(()=>C.recordPayment(w,d,{amount:100,reference:'x',confirmed:true},NOW),/authorization/);quote(d);C.accept(d,NOW);C.authorize(d,NOW);assert.throws(()=>C.recordPayment(w,d,{amount:100,reference:'x',confirmed:false},NOW),/Confirm successful/);});
test('payment references are unique across the workspace and case insensitive',()=>{const{w,d}=paid();assert.throws(()=>C.recordPayment(w,d,{amount:203800,reference:' tx-1 ',confirmed:true},NOW),/already recorded/);assert.equal(C.metrics(w).cash,203800);});
test('monthly plans keep cash collected separate from total contract value',()=>{const{w,d}=paid(true);assert.equal(C.quoteTotal(d.quote),19900);assert.equal(C.contractTotal(d.quote),238800);assert.equal(C.metrics(w).cash,19900);assert.equal(C.metrics(w).newPaidDeals,1);});
test('later installment is cash and not a second new deal',()=>{const{w,d}=paid(true);C.recordPayment(w,d,{amount:19900,reference:'TX-2',confirmed:true},'2026-11-07T15:00:00Z');assert.equal(C.metrics(w).cash,39800);assert.equal(C.metrics(w).newPaidDeals,1);const m=C.metrics(w,{from:'2026-11-07',to:'2026-11-07'});assert.equal(m.newPaidDeals,0);assert.equal(m.cash,19900);});
test('partial and full refunds reduce net cash without erasing payment history',()=>{const{w,d,p}=paid();C.recordRefund(w,d,{paymentId:p.id,amount:10000,reference:'RF-1',confirmed:true},NOW);assert.equal(C.netPaid(w,d.id),193800);assert.equal(C.status(w,d),'Partially refunded');C.recordRefund(w,d,{paymentId:p.id,amount:193800,reference:'RF-2',confirmed:true},NOW);assert.equal(C.netPaid(w,d.id),0);assert.equal(C.status(w,d),'Refunded');assert.equal(C.metrics(w).retained,0);assert.equal(C.metrics(w).newPaidDeals,1);assert.equal(C.queue(w).length,0);});
test('duplicate and excessive refunds are rejected',()=>{const{w,d,p}=paid();C.recordRefund(w,d,{paymentId:p.id,amount:10000,reference:'RF-1',confirmed:true},NOW);assert.throws(()=>C.recordRefund(w,d,{paymentId:p.id,amount:10000,reference:'rf-1',confirmed:true},NOW),/already recorded/);assert.throws(()=>C.recordRefund(w,d,{paymentId:p.id,amount:200000,reference:'RF-2',confirmed:true},NOW),/exceeds/);});
test('activation requires positive collected value',()=>{const{w,d}=authorized();assert.throws(()=>C.activate(w,d,NOW),/Confirm payment/);C.recordPayment(w,d,{amount:203800,reference:'TX-1',confirmed:true},NOW);C.activate(w,d,NOW);assert.equal(C.status(w,d),'Activated');});
test('calls cannot overlap and end outcomes determine qualification',()=>{const{w,d}=fixture();C.startSession(w,d,NOW);assert.throws(()=>C.startSession(w,d,NOW),/Finish the active/);C.endSession(w,d,'no-answer','2026-10-07T15:10:00Z');assert.equal(C.metrics(w).qualified,0);assert.equal(C.metrics(w).connected,0);assert.equal(C.metrics(w).hours,1/6);});
test('qualified close rate uses unique qualified deals, with a visible denominator',()=>{const{w,d}=paid();C.startSession(w,d,NOW);C.endSession(w,d,'connected','2026-10-07T15:10:00Z');C.startSession(w,d,'2026-10-07T16:00:00Z');C.endSession(w,d,'connected','2026-10-07T16:10:00Z');const m=C.metrics(w,{from:'2026-10-07',to:'2026-10-07'});assert.equal(m.qualified,1);assert.equal(m.closeRate,1);assert.equal(m.calls,2);});
test('reporting uses the selected time zone across midnight',()=>{const{w,d}=authorized();C.recordPayment(w,d,{amount:100,reference:'NIGHT',confirmed:true},'2026-10-08T02:00:00Z');assert.equal(C.metrics(w,{from:'2026-10-07',to:'2026-10-07'}).cash,100);assert.equal(C.metrics(w,{from:'2026-10-08',to:'2026-10-08'}).cash,0);});
test('queue prioritizes agreed callbacks and excludes no-contact and declined deals',()=>{const{w,d}=fixture();d.task={at:'2026-10-07T14:00:00Z',purpose:'Joint decision',confirmed:true,done:false};const n=C.deal({name:'New'},NOW);w.deals.push(n);assert.equal(C.queue(w,Date.parse(NOW))[0].deal.id,d.id);d.doNotContact=true;assert.equal(C.queue(w,Date.parse(NOW)).length,1);assert.throws(()=>C.startSession(w,d,NOW),/not to be contacted/);n.disposition='declined';assert.equal(C.queue(w,Date.parse(NOW)).length,0);});
test('legacy migration preserves buyer facts without inventing paid transactions',()=>{const w=C.migrateLegacy({f:{customerName:'Existing',qtp:'y',btp:'n',repName:'Chris'},n:{worry:'Unsure about filing',decider:'Partner'},cart:[{price:'$2038'}],outcome:'sold'});assert.equal(w.deals[0].facts.need,'Unsure about filing');assert.equal(w.deals[0].coverage.planning,'covered');assert.equal(w.deals[0].coverage.filing,'gap');assert.equal(w.deals[0].coverage.books,'unknown');assert.equal(w.events.length,0);assert.equal(C.metrics(w).cash,0);});
test('a follow-up draft does not invent an appointment or a quote',()=>{const{w,d}=fixture();const s=C.email(w,d);assert.ok(!s.includes('Our agreed next step'));assert.ok(!s.includes('Initial amount'));d.task={purpose:'Resolve a question',at:NOW,confirmed:false};assert.ok(C.email(w,d).includes('Proposed next step'));});
test('backup validation rejects duplicate transactions and broken refund links',()=>{const{w}=paid();w.events.push({...w.events[0],id:'duplicate'});assert.throws(()=>C.validateWorkspace(w),/duplicate transaction/);const second=paid();second.w.events.push({id:'r',type:'refund',dealId:second.d.id,paymentId:'bad',reference:'RF-X',amount:100,at:NOW});assert.throws(()=>C.validateWorkspace(second.w),/Refund history/);});
test('catalog import cannot claim quotes are verified and validates cents',()=>{const input=JSON.parse(JSON.stringify(D.catalog));input[0].verified=true;assert.equal(D.validateCatalog(input)[0].verified,false);input[0].annual=[12.3,15];assert.throws(()=>D.validateCatalog(input),/integer cents/);});
test('money is represented in integer cents',()=>{assert.equal(C.cents('19.99'),1999);assert.equal(C.cents('0.01'),1);for(const bad of ['-1','0','1.999','NaN','1e5','1,000'])assert.throws(()=>C.cents(bad));});
test('practice workspace has valid isolated records and plausible outcomes',()=>{const w=D.demo(C);assert.equal(C.validateWorkspace(w).version,3);assert.equal(w.deals.length,5);assert.equal(C.metrics(w).newPaidDeals,2);assert.equal(C.metrics(w).cash,49900);assert.equal(C.metrics(w).activated,1);});
