(function(root,factory){const data=factory();if(typeof module==='object'&&module.exports)module.exports=data;else root.RevDeskData=data;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
// Historical figures from the original guide. Account-level verification is always required.
const catalog=[
{id:'bundle',name:'Complete Tax Bundle',services:['planning','filing','books'],annual:[203800,253800],monthly:[19900,24900],scope:'Quarterly tax planning, tax preparation and filing, and Money Pro. Confirm entity-specific return scope and all inclusions.'},
{id:'dify',name:'Planning + Filing',services:['planning','filing'],annual:[179800,229800],monthly:[16900,21900],scope:'Quarterly planning plus tax preparation and filing. Confirm entity-specific return scope and all inclusions.'},
{id:'diy',name:'Planning + Money Pro',services:['planning','books'],annual:[113900,null],monthly:null,scope:'Quarterly planning and Money Pro. Customer handles filing. Confirm eligibility and included services.'},
{id:'planning',name:'Quarterly Tax Planning',services:['planning'],annual:[89900,139900],monthly:[8900,11900],scope:'Quarterly sessions with a tax professional. Confirm session availability, eligibility, and current scope.'},
{id:'filing',name:'Business Tax Prep & Filing',services:['filing'],annual:[89900,89900],monthly:null,scope:'Business tax preparation and filing. Confirm which business and personal returns are included for this entity.'},
{id:'books',name:'Money Pro',services:['books'],annual:[30000,30000],monthly:[3000,3000],scope:'Bookkeeping, expense and mileage tracking, and invoicing tools. Confirm supported connections and current capabilities.'},
{id:'agent',name:'Registered Agent',services:['agent'],annual:[19900,19900],monthly:null,scope:'Registered agent service. Confirm state availability, address use, service scope, and any change fees.'},
{id:'ein',name:'EIN Filing Service',services:['ein'],annual:[9900,9900],monthly:null,once:true,scope:'Assistance obtaining an EIN. Explain the service fee and the customer’s direct application option.'},
{id:'agreement',name:'Operating Agreement',services:['agreement'],annual:[9900,9900],monthly:null,once:true,scope:'Operating agreement service. Confirm customization and review scope; do not represent it as individual legal advice.'},
{id:'licenses',name:'Business License Report',services:['licenses'],annual:[14900,14900],monthly:null,once:true,scope:'A report identifying licensing information. Confirm scope; a report is not the purchase or issuance of a license.'},
{id:'website',name:'Website Services',services:['website'],annual:[null,null],monthly:null,scope:'Verify the current website package, deliverables, hosting, domain terms, and eligibility in the approved system.'}
].map((p,i)=>({...p,order:i,source:'June 2026 training guide · reference only',version:'2026-06',verified:false}));
const playbook=[
['open','Open','Earn the conversation','Agree on purpose, available time, and a useful outcome.','What would make this a useful conversation for you today?','The customer’s agenda and whether they have time.','Use the approved introduction and recording disclosure when applicable. If time is short, agree on one priority and a next step.'],
['discovery','Discover','Find the priority','Understand the business and the person making the decision.','What inspired you to start this business, and what are you most focused on getting right?','Specific plans, concerns, and existing support.','Follow an important answer with “Tell me more about that.” Capture the customer’s words.'],
['verify','Discover','Verify the account','Understand the actual account before recommending a service.','What help do you already have in place, either with us or with another provider?','Confirmed coverage, provider scope, and unanswered questions.','Check the approved account record. Keep unknown, covered, confirmed gap, and not relevant distinct.'],
['order','Discover','Review the order','Make sure the customer understands what they already bought.','What questions do you have about the services already on your account?','Confusion, missing activation, or an unmet expectation.','Resolve existing order questions before introducing a new recommendation.'],
['impact','Discover','Explore the impact','Understand why the customer’s priority matters.','What would getting that handled change for you or the business?','The customer’s own description of time, work, uncertainty, or outcomes.','Use their explanation. Avoid inventing consequences or deadlines.'],
['agent','Services','Registered agent','Confirm the current arrangement and whether it works for them.','Who is handling your registered agent responsibilities now, and how is that working for you?','The existing provider, responsibilities understood, and any actual concern.','Verify state-specific scope. Recommend a change only when it addresses a confirmed need.'],
['tax','Services','Tax discovery','Learn how the customer plans to handle taxes throughout the year.','What help do you have with decisions during the year and with filing at the end of it?','Separate planning from preparation and filing.','An accountant’s presence alone does not establish a gap or complete coverage. Ask about the scope.'],
['education','Services','Relevant education','Answer the customer’s actual questions.','Which part of that would be most useful to understand?','A specific question that an approved explanation can address.','Use current approved materials. Route individual tax and legal decisions to the appropriate professional.'],
['qualify','Discover','Confirm the need','Find out whether the customer wants help with the confirmed gap.','Is this something you want help getting handled, or are you comfortable with your current plan?','A genuine need, a preference to do it themselves, or no present fit.','A clear no is useful information. Update the deal and choose an appropriate next step.'],
['solution','Recommend','Explain one fitting option','Connect the verified service to what the customer asked for.','You said [their priority]. This option addresses that through [verified capability]. How well does that fit?','Specific value, missing scope, or overlap with existing services.','Show the relevant scope, verified terms, initial charge, and total commitment.'],
['close','Commit','Ask for the decision','Make the choice clear and give the customer room to answer.','Based on what you wanted to solve, I recommend [option] at [verified price and terms]. Would you like to get that started?','Agreement, a question, an objection, or a decline.','Pause after the question. A quiet moment does not establish a price objection.'],
['books','Services','Money Pro','Understand how the customer keeps business records.','How are you tracking income, expenses, receipts, and mileage today?','A working system, a workflow gap, or an outside bookkeeper.','Recommend only verified capabilities that address their gap.'],
['setup','Services','EIN, agreement, and licenses','Identify an actual setup need.','Which of these pieces are already handled, and where would you like help?','Confirmed account status and customer preference.','Clarify exactly what the service provides, what it costs, and any direct or outside options.'],
['pay','Commit','Authorize and confirm payment','Keep acceptance, authorization, and successful payment distinct.','To confirm, we’re adding [service] for [amount and terms]. Do I have your permission to proceed?','Explicit permission to the exact terms.','Process payment only in the approved system. Record its successful transaction reference here. Never store card details.'],
['activate','Activate','Get the first step completed','Help the customer begin using the service.','Can you open your dashboard so we can complete the first step together?','Actual access, booking, or activation confirmation.','Verify activation in the service system. Schedule assistance if needed.'],
['follow','Follow up','Agree on the next event','Leave a clear purpose, owner, and time.','Would it help to reconnect once [specific issue] is resolved? What time works for you?','Actual agreement and the right participants.','Separate an internal reminder from an agreed callback. Record the promise and its due time.'],
['objection','Clarify','Diagnose the concern','Understand the objection before choosing a response.','What part is giving you pause?','Cost, value, timing, trust, approval, or a clear desire to stop.','Acknowledge, clarify, answer with relevant evidence, and check whether the concern was resolved.'],
['recap','Follow up','Leave a useful recap','Make the next conversation easy to continue.','What questions remain before we finish?','Unresolved issues and promises you made.','Copy the prepared recap into Salesforce and review the follow-up draft before sending. Revenue Desk does not send messages.']
].map(([id,section,title,goal,ask,listen,move])=>({id,section,title,goal,ask,listen,move}));
function demo(C){
const w=C.workspace();w.settings.repName='Chris';const now=Date.now(),at=m=>new Date(now+m*60000).toISOString();
function customer(name,business,lane='tax'){const d=C.deal({name,business,industry:'Sample business',entity:'single',source:'Practice workspace'},at(-200));d.lane=lane;d.permission=true;d.facts={need:'I want the business finances organized before my first busy season',impact:'I want to spend my time with customers',timing:'Before next month',decision:'I make this decision',fit:'',criterion:''};d.decisionType='solo';d.coverage.planning='gap';d.coverage.filing='gap';d.coverage.books='gap';w.deals.push(d);return d;}
function quote(d,p,amount){C.saveQuote(d,{id:C.uid(),lines:[{productId:p.id,name:p.name,amount,services:p.services,billing:'annual',months:12}],scope:'Practice only: '+p.scope,terms:'Annual service; automatic annual renewal. Fictional practice terms.',source:'DEMO · fictional account verification',verified:true,verifiedAt:at(-120),expiresAt:at(7*1440)},at(-120));}
function call(d,m,qualified=true){w.sessions.push({id:C.uid(),dealId:d.id,startedAt:at(-m-18),endedAt:at(-m),seconds:1080,outcome:'connected',qualified,cohort:d.cohort});}
const a=customer('Avery Brooks','Northline Studio');a.facts.need='I want help planning during the year, not just filing';a.objection={category:'cost',quote:'It sounds useful. I’m just watching cash flow right now.',clarification:'',resolved:false,resolution:''};quote(a,catalog[0],203800);a.task={id:C.uid(),kind:'callback',at:at(-12),purpose:'Clarify the budget concern and review the fitting option',owner:'Chris',confirmed:true,done:false};C.addHistory(a,'Customer agreed to follow-up',at(-80));call(a,80);
const b=customer('Jordan Ellis','Fieldwork Collective');b.facts.decision='My business partner and I decide together';b.decisionType='shared';b.task={id:C.uid(),kind:'callback',at:at(75),purpose:'Answer both partners’ questions',owner:'Chris',confirmed:true,done:false};C.addHistory(b,'Customer agreed to follow-up',at(-70));call(b,70);
const c=customer('Taylor Reed','Cedar & Coast','agent');c.coverage.agent='gap';c.facts.need='I want help handling registered agent responsibilities';c.facts.fit='That service addresses the responsibility I want help with';c.facts.criterion='I understand the terms';quote(c,catalog[6],19900);C.accept(c,at(-100));C.authorize(c,at(-99));C.recordPayment(w,c,{amount:19900,reference:'DEMO-1001',confirmed:true},at(-98));call(c,95);
const d=C.deal({name:'Casey Morgan',business:'Goodkind Services',source:'Practice workspace'},at(-25));w.deals.push(d);
const e=customer('Riley Park','Open Road Design','books');e.facts.need='I need one place to keep my receipts and invoices';e.facts.fit='This covers the tracking I need';e.facts.criterion='The scope and renewal terms are clear';quote(e,catalog[5],30000);C.accept(e,at(-60));C.authorize(e,at(-59));C.recordPayment(w,e,{amount:30000,reference:'DEMO-1002',confirmed:true},at(-58));C.activate(w,e,at(-50));call(e,48);
w.activeId=a.id;return w;
}
function validateCatalog(value){
if(!Array.isArray(value)||!value.length||value.length>100)throw new Error('The catalog must be a JSON array with 1–100 products.');const ids=new Set(),services=['planning','filing','books','agent','ein','agreement','licenses','website'];
for(const p of value){if(typeof p.id!=='string'||ids.has(p.id)||typeof p.name!=='string'||!Array.isArray(p.services)||!p.services.length||p.services.some(k=>!services.includes(k))||typeof p.scope!=='string'||typeof p.source!=='string'||!p.source.trim())throw new Error('Each unique product needs a name, services, scope, and source.');ids.add(p.id);for(const prices of [p.annual,p.monthly])if(prices!==null&&(!Array.isArray(prices)||prices.length!==2||prices.some(n=>n!==null&&(!Number.isSafeInteger(n)||n<=0||n>100000000))))throw new Error('Prices use integer cents: [single-member, multi-member], or null.');}
return value.map((p,i)=>({id:p.id,name:p.name,services:[...p.services],annual:p.annual,monthly:p.monthly,scope:p.scope,source:p.source,version:p.version||'Imported',once:!!p.once,order:Number.isFinite(p.order)?p.order:i,verified:false}));
}
return{catalog,playbook,demo,validateCatalog};
});
