/* Open call workspace. Navigation never depends on evidence or deal milestones. */
(function(root){
'use strict';
const sections=[
 ['overview','At a glance','CALL MAP','grid','summary dashboard'],
 ['open','Introduction','DISCOVER','phone','opening permission time'],
 ['discovery','Discovery & decision','DISCOVER','target','need impact timing authority partner'],
 ['account','Account & coverage','DISCOVER','shield','order review provider'],
 ['tax','Tax discovery','SERVICES','book','planning filing accountant'],
 ['education','Tax education','SERVICES','book','quarterly classification deductions'],
 ['agent','Registered agent','SERVICES','shield','compliance address'],
 ['books','Money Pro','SERVICES','wallet','bookkeeping expenses receipts'],
 ['setup','EIN, agreement & licenses','SERVICES','grid','operating agreement business license report'],
 ['website','Website','SERVICES','grid','online domain'],
 ['offers','Products & pricing','DECISION','wallet','bundle plans alternatives solutions catalog'],
 ['objections','Objections','DECISION','message','cost expensive think partner approval timing value trust'],
 ['close','Ask for the decision','DECISION','check','close accept yes decline'],
 ['payment','Payment & authorization','NEXT STEPS','wallet','charge transaction refund'],
 ['activate','Schedule & activate','NEXT STEPS','check','consultation session booking'],
 ['follow','Next event','NEXT STEPS','clock','follow up callback task'],
 ['recap','Notes & recap','REFERENCE','edit','salesforce email copy'],
 ['history','Deal timeline','REFERENCE','clock','history events'],
 ['reference','Reference desk','REFERENCE','book','guide practice shortcuts']
].map(([id,title,group,icon,keywords])=>({id,title,group,icon,keywords}));

function create(ctx){
 const {C,D,h,attr,icon,btn,pill,stamp,initials,typeStatus}=ctx;
 const jump=(title,id,cls='small ghost')=>btn(title,'desk-jump',cls,'data-section="'+id+'"');
 const record=(d,title,action,extra='',cls='small ghost')=>btn(title,d?action:'new-deal',cls,d?extra:'');
 const guide=id=>D.playbook.find(p=>p.id===id);
 const prompt=(label,words,note='')=>'<div class="desk-prompt"><span class="eyebrow">'+h(label)+'</span><p>“'+h(words)+'”</p>'+(note?'<small>'+h(note)+'</small>':'')+'</div>';
 const hint=(title,text)=>'<div class="desk-hint"><strong>'+h(title)+'</strong><p>'+h(text)+'</p></div>';
 const script=(id,extra='')=>{const p=guide(id);return prompt('Ask / say',p.ask)+hint('Listen for',p.listen)+extra;};
 const coverage=(d,key)=>d?d.coverage[key]:'unknown';
 const coverageLabel=state=>({unknown:'Unknown',gap:'Confirmed gap',covered:'Already covered',na:'Not relevant'}[state]);
 const fact=(d,key,placeholder)=>'<button class="fact-tile" data-action="'+(d?'evidence':'new-deal')+'" data-key="'+key+'"><span>'+h(C.FACTS[key])+icon(d?.facts[key]?'check':'plus')+'</span><strong class="'+(d?.facts[key]?'':'muted')+'">'+h(d?.facts[key]||placeholder)+'</strong></button>';

 function render(d){
  const {data,section,focus,coachVisible,practice}=ctx.state(),s=data.sessions.find(s=>!s.endedAt),isLive=s&&s.dealId===d?.id;
  const elapsed=s?Math.max(0,Math.floor((Date.now()-Date.parse(s.startedAt))/1000)):0;
  const timer=Math.floor(elapsed/60).toString().padStart(2,'0')+':'+(elapsed%60).toString().padStart(2,'0');
  const all=focus?sections.filter(x=>x.id===section):sections;
  let group='';
  const map=sections.map((item,i)=>{const label=item.group!==group?'<div class="map-group">'+h(item.group)+'</div>':'';group=item.group;return label+'<button class="map-item '+(section===item.id?'active':'')+'" data-action="desk-jump" data-section="'+item.id+'" '+(section===item.id?'aria-current="location"':'')+'><span class="map-number">'+String(i).padStart(2,'0')+'</span><span>'+h(item.title)+'</span>'+icon('chevron')+'</button>';}).join('');
  return '<div class="desk-page"><header class="open-desk-head"><div class="row"><div class="avatar large">'+(d?initials(d.name):icon('phone'))+'</div><div><div class="row wrap"><h1>'+h(d?.name||'Your call desk')+'</h1>'+(d?typeStatus(d):pill('Explore freely'))+'</div><p>'+h(d?[d.business,d.industry].filter(Boolean).join(' · '):'Every script, product, and closing tool. Jump wherever the conversation goes.')+'</p></div></div><div class="row wrap desk-customer-actions">'+record(d,icon('edit')+' '+(d?'Customer':'Add customer'),'edit-deal')+(d?btn(icon('grid')+' Switch','switch-deal','small ghost'):'')+(isLive?'<span class="live-pill"><i class="dot"></i><span data-timer>'+timer+'</span></span>'+btn('End call','end-call','small'):record(d,icon('phone')+' Start call','start-call','','small primary'))+'</div></header>'+
   '<div class="desk-commandbar"><button class="jump-search" data-action="jump-search">'+icon('search')+'<span>Jump to anything</span><kbd>⌘ / Ctrl K</kbd></button><div class="desk-hotlinks" aria-label="Quick jumps">'+jump('Tax','tax')+jump('Products','offers')+jump('Objections','objections')+jump('Payment','payment')+jump('Recap','recap')+'</div><button class="btn small ghost support-toggle" data-action="call-support">'+icon('edit')+' Call support</button><div class="desk-view-switch" aria-label="Desk display">'+btn('All sections','desk-mode',!focus?'small selected':'small','data-mode="all" aria-pressed="'+(!focus)+'"')+btn('Focus','desk-mode',focus?'small selected':'small','data-mode="focus" aria-pressed="'+focus+'"')+'</div></div>'+
   '<div class="open-desk"><aside class="call-map" aria-label="Call map"><div class="map-heading"><h2>Jump anywhere</h2><span>'+sections.length+' sections</span></div><nav aria-label="Call sections">'+map+'</nav><div class="map-foot">No required order.<br><kbd>F</kbd> focus · <kbd>O</kbd> objections</div></aside><div class="desk-scroll" id="desk-scroll" tabindex="-1" aria-label="Call workspace">'+all.map(item=>'<section class="desk-section" id="desk-'+item.id+'" tabindex="-1" data-desk-section="'+item.id+'"><div class="desk-section-head"><div><span class="eyebrow">'+h(item.group)+'</span><h2>'+h(item.title)+'</h2></div><button class="iconbtn" data-action="desk-focus-section" data-section="'+item.id+'" aria-label="Focus on '+h(item.title)+'" title="Focus on this section">'+icon('target')+'</button></div>'+content(item.id,d)+'</section>').join('')+'<div class="desk-end">You can revisit any section. Your place and customer notes stay with you.</div></div><aside class="desk-copilot" aria-label="Call support">'+support(d)+'</aside></div></div>';
 }

 function content(id,d){
  const {data,catalog}=ctx.state(),a=d?C.action(data,d,catalog):null;
  if(id==='overview')return '<div class="overview-banner"><div><span class="eyebrow">OPEN CALL WORKSPACE</span><h3>Your conversation.<br>Your order.</h3><p>Start anywhere. Keep the customer in view.</p></div><div class="open-orbit" aria-hidden="true">'+icon('phone')+'</div></div>'+
   '<div class="desk-facts">'+fact(d,'need','What matters to them?')+fact(d,'timing','Why now?')+fact(d,'decision','Who needs to agree?')+'</div>'+
   '<div class="section-shortcuts">'+[['tax','Tax discovery','Understand their setup','book'],['offers','Products & pricing','See every option','wallet'],['objections','Handle a concern','Find the real question','message'],['payment','Payment','Confirm the outcome','check']].map(([key,title,sub,i])=>'<button data-action="desk-jump" data-section="'+key+'">'+icon(i)+'<span><b>'+title+'</b><small>'+sub+'</small></span>'+icon('arrow')+'</button>').join('')+'</div>'+
   (d?.objection&&!d.objection.resolved?'<div class="overview-concern"><div><span class="eyebrow">OPEN CONCERN</span><p>“'+h(d.objection.quote)+'”</p></div>'+jump('Open response','objections')+'</div>':'')+
   '<div class="desk-overview-footer"><span>'+icon('spark')+' Suggestions live in your call support panel.</span>'+btn('Open optional guide','guided','small ghost')+'</div>';
  if(id==='open')return prompt('Set the agenda','Hi '+(d?.name?.split(' ')[0]||'[customer]')+', this is '+(data.settings.repName||'[your name]')+' with ZenBusiness. What would make this a useful conversation for you today?','Use the approved introduction and any required disclosure.')+prompt('Agree on the time','Do you have a few minutes now, or would another time work better?')+'<div class="desk-action-row">'+record(d,'Time & purpose agreed','permission','data-value="yes"','small primary')+record(d,'Short on time','permission','data-value="rushed"')+jump('Set another time','follow')+(d?.permission?pill(d.rushed?'Brief conversation agreed':'Conversation agreed','good'):'')+'</div>';
  if(id==='discovery')return '<p class="section-intro">Use what is relevant. Capture an answer whenever it comes up.</p><div class="discovery-prompts">'+[
   ['need','What are you most focused on getting right in the business?'],['impact','What would having that handled change for you?'],['timing','When would you want this in place, and what makes that timing matter?'],['decision','How do you and anyone else involved usually make this kind of decision?'],['fit','How well does this address what you wanted help with?'],['criterion','What would you need to know to feel comfortable deciding?']
  ].map(([key,q])=>'<div>'+prompt(C.FACTS[key],q)+record(d,d?.facts[key]?'Edit: '+d.facts[key]:'Capture '+C.FACTS[key].toLowerCase(),'evidence','data-key="'+key+'"')+'</div>').join('')+'</div>';
  if(id==='account')return script('verify')+(d?'<div class="conversation-lane"><label for="lane">Coach focus</label><select id="lane">'+Object.entries({tax:'Tax services',agent:'Registered agent',books:'Money Pro',setup:'Business setup',website:'Website'}).map(([key,label])=>'<option value="'+key+'" '+(d.lane===key?'selected':'')+'>'+label+'</option>').join('')+'</select><small>Changes suggestions. Every section stays available.</small></div>':'')+'<div class="coverage-board">'+Object.entries(C.SERVICES).map(([key,label])=>'<button data-action="'+(d?'coverage':'new-deal')+'"><span>'+h(label)+'</span><em class="'+coverage(d,key)+'">'+coverageLabel(coverage(d,key))+'</em>'+(d?.coverageNotes[key]?'<small>'+h(d.coverageNotes[key])+'</small>':'')+'</button>').join('')+'</div><div class="desk-action-row">'+record(d,'Update account coverage','coverage','','small primary')+record(d,'Customer details','edit-deal')+'</div>';
  if(id==='tax')return script('tax')+'<div class="desk-two-up">'+prompt('Planning during the year','When a tax question comes up during the year, who helps you work through it?')+prompt('Filing at year end','Who is preparing and filing the returns, and what is included?')+'</div>'+prompt('Records underneath it','How are you keeping the records that person will need?')+hint('Connect the dots','Confirm which parts are already handled. Explore the parts the customer actually wants help with.')+'<div class="desk-action-row">'+record(d,'Capture their priority','evidence','data-key="need"')+record(d,'Update coverage','coverage')+jump('Explore tax options','offers')+'</div>';
  if(id==='education')return '<p class="section-intro">Choose the topic they care about, use an approved explanation, then check their understanding.</p><div class="education-grid">'+[
   ['Business structure','What have you been told about how this business is treated for tax purposes?','Clarify their question; a tax professional confirms the treatment for their situation.'],
   ['Planning through the year','How are you planning for what you may owe as income starts coming in?','Use the current approved explanation of planning and estimated payments.'],
   ['Expenses & records','What business expenses have you started tracking so far?','Explain record organization. A professional determines the treatment of specific expenses.'],
   ['Professional support','What would you want to be able to ask a tax professional before year end?','Connect only the verified service scope to the question they named.']
  ].map(([label,q,note])=>'<div>'+prompt(label,q,note)+'</div>').join('')+'</div>'+prompt('Check the value','Which part of that would be most useful for your business?')+record(d,'Capture what matters','evidence','data-key="impact"');
  if(['agent','books','website'].includes(id)){
   const prompts={agent:['agent','What, if anything, would you want to change about the arrangement you have now?'],books:['books','Where does that process take more time or effort than you would like?'],website:[null,'What do you need customers to be able to find or do online?']},p=prompts[id];
   return (p[0]?script(p[0]):prompt('Start with the need',p[1]))+(p[0]?prompt('Explore the gap',p[1]):hint('Verify the package','Check deliverables, account access, domain and hosting terms before recommending a website service.'))+serviceRow(d,id)+record(d,'Capture their priority','evidence','data-key="need"');
  }
  if(id==='setup')return script('setup')+['ein','agreement','licenses'].map(key=>serviceRow(d,key)).join('');
  if(id==='offers')return products(d);
  if(id==='objections')return objections(d);
  if(id==='close'){
   const q=d?.quote,ready=d?C.commitReady(d):'Add a customer to save the decision.';
   return prompt('Connect the recommendation',d?.facts.need?'You said “'+d.facts.need+'”. Based on that, I recommend '+(q?q.lines.map(l=>l.name).join(' + '):'[the fitting option]')+'. How well does that match what you wanted?':'You said [their priority]. This option addresses it through [verified capability]. How well does that match what you wanted?')+
    prompt('Ask clearly',q&&C.quoteValid(q)?'The initial amount is '+C.money(C.quoteTotal(q))+', with a total commitment of '+C.money(C.contractTotal(q))+'. '+q.terms+' Would you like to get this started?':'With [verified scope, price, and terms] clear, would you like to get this started?')+
    '<div class="desk-action-row">'+btn(icon('pause')+' Pause & listen','silence','small ghost','data-silence')+jump('They have a concern','objections')+'</div>'+hint('Record what happened',ready||'The supporting details are captured. Record the customer’s actual decision.')+'<div class="desk-action-row">'+record(d,'Customer agreed','accept','','small primary')+record(d,'Customer declined','decline')+jump('Review the offer','offers')+'</div>';
  }
  if(id==='payment')return payment(d);
  if(id==='activate')return script('activate')+'<div class="desk-action-row">'+record(d,'Confirm completed activation','activate','','small primary')+record(d,'Schedule the first session','task')+'</div>'+(d?.activatedAt?'<div class="notice">Activation confirmed '+h(stamp(d.activatedAt))+'.</div>':'');
  if(id==='follow')return script('follow')+(d?.task?'<div class="follow-summary"><strong>'+h(d.task.purpose)+'</strong><p>'+h(stamp(d.task.at))+' · '+h(d.task.owner)+'</p>'+pill(d.task.done?'Completed':d.task.confirmed?'Customer agreed':'Internal reminder',d.task.done?'good':'')+'</div>':'')+'<div class="desk-action-row">'+record(d,d?.task?'Edit next event':'Set the next event','task','','small primary')+(d?.task&&!d.task.done?record(d,'Mark complete','complete-task'):'')+'</div>';
  if(id==='recap')return d?'<div class="recap-tools">'+record(d,'Edit working notes','notes')+btn(icon('copy')+' Copy Salesforce recap','copy-recap','small primary')+btn('Copy follow-up draft','copy-email','small ghost',d.doNotContact?'disabled':'')+'</div><label for="recap-text">Salesforce recap</label><textarea id="recap-text" readonly class="copy-block">'+h(C.recap(data,d))+'</textarea><p class="explanation">Prepared for review and pasting into Salesforce. No CRM update has been sent.</p>'+(!d.doNotContact?'<details class="email-preview"><summary>Read the follow-up draft</summary><textarea readonly class="copy-block" aria-label="Follow-up email draft">'+h(C.email(data,d))+'</textarea></details>':'<p class="notice warn">This customer asked not to be contacted.</p>'):prompt('Leave a useful recap',guide('recap').ask)+hint('Your notes stay with the customer','Add a customer to save notes, prepare a Salesforce recap, and draft a follow-up.')+btn('Add customer','new-deal','small primary');
  if(id==='history')return d?'<div class="timeline">'+[...d.history].reverse().map(e=>'<div class="timeline-item">'+h(e.message)+'<small>'+h(stamp(e.at))+'</small></div>').join('')+'<div class="timeline-item">Deal created<small>'+h(stamp(d.createdAt))+'</small></div></div>':'<p class="section-intro">Customer updates appear here as you record them. Browsing the desk does not create a deal.</p>';
  if(id==='reference')return '<div class="reference-links"><a class="btn ghost" href="junecallguideofficial.html" target="_blank" rel="noopener">'+icon('book')+' Original training guide '+icon('arrow')+'</a>'+btn('Browse the playbook','nav','ghost','data-view="playbook"')+btn('Practice an objection','practice-drill','ghost','data-category="thinking"')+btn('Catalog sources','catalog','ghost')+'</div><div class="shortcuts-table"><span>Search sections and actions</span><kbd>⌘ / Ctrl K</kbd><span>Toggle focus view</span><kbd>F</kbd><span>Objection library</span><kbd>O</kbd><span>Products & pricing</span><kbd>P</kbd><span>Working notes</span><kbd>M</kbd><span>Previous / next section</span><kbd>Alt ← / →</kbd></div><p class="explanation">Shortcuts stay inactive while you type. Prices in the reference catalog must be verified for the current account.</p>';
  return '';
 }

 function serviceRow(d,id){
  const p=ctx.state().catalog.find(x=>x.id===id);if(!p)return '';
  const state=coverage(d,id),notes={ein:'Ask whether an EIN is already assigned. Explain the paid assistance and the direct application option.',agreement:'Ask what is already in place and what help they want with the agreement.',licenses:'Clarify whether they need a report identifying requirements. A report does not issue licenses.',agent:'Confirm the current provider and the actual responsibilities they want help with.',books:'Connect the verified tools to their existing workflow.',website:'Confirm the current package and the customer’s own online goals.'};
  return '<div class="service-row"><div><div class="row wrap"><h3>'+h(p.name)+'</h3>'+pill(coverageLabel(state),state==='gap'?'good':'')+'</div><p>'+h(notes[id])+'</p></div><div class="desk-action-row">'+record(d,'Coverage','coverage')+jump('Compare options','offers')+'</div></div>';
 }

 function products(d){
  const {catalog}=ctx.state(),q=d?.quote,rec=d?C.recommendation(d,catalog):null,index=d?.entity==='multi'?1:0;
  let current='';
  if(q)current='<div class="current-offer"><div class="between wrap"><span class="eyebrow">CURRENT RECOMMENDATION</span>'+pill(C.quoteValid(q)?'Price verified':'Reverification needed',C.quoteValid(q)?'good':'warn')+'</div><h3>'+h(q.lines.map(l=>l.name).join(' + '))+'</h3><p>'+h(q.scope)+'</p><div class="quote-amounts"><span><b>'+C.money(C.quoteTotal(q))+'</b> initial amount</span><span><b>'+C.money(C.contractTotal(q))+'</b> total commitment</span></div><p>'+h(q.terms)+'</p><small>Source: '+h(q.source)+' · valid until '+h(stamp(q.expiresAt))+'</small><div class="desk-action-row">'+(!d.acceptedAt?record(d,'Edit / reverify','quote','data-product="'+attr(q.lines[0].productId)+'"')+record(d,'Remove recommendation','remove-quote'):C.grossPaid(ctx.state().data,d.id)===0?record(d,'Reopen offer','unlock-offer'):'')+jump('Ask for the decision','close','small primary')+'</div></div>';
  else if(rec)current='<div class="recommended-strip"><div>'+icon('spark')+' <b>Suggested fit: '+h(rec.name)+'</b><small>Based on the recorded need and confirmed gaps. Needs price verification.</small></div>'+record(d,'Verify offer','quote','data-product="'+attr(rec.id)+'"','small primary')+'</div>';
  return current+'<div class="between wrap catalog-heading"><div><h3>Every option, always available</h3><p>Browse now. Confirm fit and current terms before making an offer.</p></div>'+record(d,'Review coverage','coverage')+'</div><div class="catalog-entity"><span>Reference pricing for</span>'+['single','multi'].map((v,i)=>btn(i?'Multi-member / other':'Single-member','catalog-entity',ctx.state().catalogEntity===v||!ctx.state().catalogEntity&&index===i?'small selected':'small ghost','data-entity="'+v+'"')).join('')+'</div><div class="product-grid">'+catalog.map(p=>{
   const idx=ctx.state().catalogEntity==='multi'?1:ctx.state().catalogEntity==='single'?0:index,price=p.annual?.[idx],monthly=p.monthly?.[idx],fit=d&&p.services.every(k=>d.coverage[k]==='gap');
   return '<article class="product-card '+(rec?.id===p.id?'suggested':'')+'"><div class="between">'+pill(p.once?'One-time service':'Ongoing service')+(fit?pill('Matches gaps','good'):'')+'</div><h3>'+h(p.name)+'</h3><p>'+h(p.scope)+'</p><div class="reference-price">'+(price?'<b>'+C.money(price)+'</b><span> / '+(p.once?'service':'year')+'</span>':'<b class="unpriced">Confirm current price</b>')+'</div>'+(monthly?'<small class="reference-monthly">Reference monthly option: '+C.money(monthly)+'</small>':'')+'<div class="product-coverage">'+p.services.map(k=>'<span class="'+coverage(d,k)+'">'+h(C.SERVICES[k])+' · '+h(coverageLabel(coverage(d,k)))+'</span>').join('')+'<small class="catalog-source">'+h(p.source)+'</small>'+record(d,d?'Review & verify':'Add customer to build offer','quote','data-product="'+attr(p.id)+'"','small ghost wide')+'</article>';
  }).join('')+'</div><p class="explanation">Reference amounts are not current quotes. Imported catalog sources appear on each option. Verify account eligibility, billing, service scope, renewal and cancellation terms before presenting a price.</p>';
 }

 function objections(d){
  const current=d?.objection;
  return (current?'<div class="current-concern"><div class="between wrap"><span class="eyebrow">THE CUSTOMER SAID</span>'+pill(current.resolved?'Resolved':'Open concern',current.resolved?'good':'warn')+'</div><p>“'+h(current.quote)+'”</p>'+record(d,'Edit this concern','objection')+'</div>':'')+'<p class="section-intro">Pick the concern you heard. Clarify it, answer the actual question, then check whether that helped.</p><div class="objection-library">'+Object.entries(C.OBJECTIONS).map(([key,o])=>'<article><h3>'+h(o.label)+'</h3>'+prompt('Ask to clarify',o.question)+'<p class="listen-for"><b>Listen for</b> '+h(o.listen)+'</p><div class="desk-action-row">'+record(d,'Capture this concern','objection','data-category="'+key+'"')+btn('Practice','practice-drill','small ghost','data-category="'+key+'"')+'</div></article>').join('')+'</div>';
 }

 function payment(d){
  const {data}=ctx.state(),q=d?.quote,net=d?C.netPaid(data,d.id):0;
  return prompt('Confirm authorization',q&&C.quoteValid(q)?'To confirm, we are adding '+q.lines.map(l=>l.name).join(' + ')+' for '+C.money(C.quoteTotal(q))+' initially. '+q.terms+' Do I have your permission to proceed?':'To confirm, we are adding [service] for [exact charge and disclosed terms]. Do I have your permission to proceed?')+'<div class="payment-status">'+[['Verified offer',q&&C.quoteValid(q),'offers'],['Customer agreed',d?.acceptedAt,'close'],['Authorized',d?.authorizedAt,'payment'],['Payment confirmed',net>0,'payment']].map(([title,done,key])=>'<button class="'+(done?'done':'')+'" data-action="desk-jump" data-section="'+key+'">'+icon(done?'check':'clock')+'<span>'+title+'</span></button>').join('')+'</div><div class="desk-action-row">'+record(d,'Record authorization','authorize')+record(d,'Record confirmed payment','payment','','small primary')+(net>0?record(d,'Record a refund','refund'):'')+'</div><div class="payment-ledger"><div class="between"><span class="eyebrow">PAYMENT RECORDS</span><strong>Net collected '+C.money(net)+'</strong></div>'+(d?data.events.filter(e=>e.dealId===d.id).map(e=>'<div class="mini-row"><span>'+h(e.type==='payment'?'Collected':'Refunded')+' · '+h(e.reference)+'<small>'+h(stamp(e.at))+'</small></span><b>'+C.money(e.amount)+'</b></div>').join(''):'')+'</div><p class="explanation">Process the charge in your approved system, then record its successful reference here. Agreement and authorization alone do not count as paid revenue.</p>';
 }

 function support(d,modal=false){
  const notesId=modal?'modal-call-notes':'call-notes';
  const {data,catalog,coachVisible}=ctx.state(),a=d?C.action(data,d,catalog):null,q=d?.quote,net=d?C.netPaid(data,d.id):0;
  return '<section class="support-card coach-card"><div class="between"><span class="eyebrow">'+icon('spark')+' OPTIONAL COACH</span><button class="iconbtn" data-action="toggle-coach" aria-label="'+(coachVisible?'Hide':'Show')+' coaching suggestion" aria-expanded="'+coachVisible+'">'+icon(coachVisible?'close':'plus')+'</button></div>'+(coachVisible?'<h3>'+h(a?.title||'Follow their priority')+'</h3><p>'+h(a?.question||'What would make this conversation useful for you?')+'</p><div class="desk-action-row">'+(a?jump('Go to suggestion',suggestedSection(a)):'')+btn('Open guide','guided','small ghost')+'</div>':'<small>Available whenever you want a prompt.</small>')+'</section><section class="support-card support-notes"><div class="between"><label for="'+notesId+'">Working notes</label>'+record(d,icon('edit'),'notes','','small ghost')+'</div><textarea id="'+notesId+'" '+(!d?'disabled':'')+' placeholder="'+(d?'Capture anything. Keep talking.':'Add a customer to save notes.')+'">'+h(d?.notes||'')+'</textarea><small>'+(d?'Saves as you type · stays with this customer':'Browse without creating a customer.')+'</small></section><section class="support-card support-snapshot"><div class="between"><h3>Buyer snapshot</h3>'+record(d,'Edit','evidence')+'</div>'+Object.entries(C.FACTS).map(([k,label])=>'<button data-action="'+(d?'evidence':'new-deal')+'" data-key="'+k+'"><span>'+h(label)+'</span><strong class="'+(d?.facts[k]?'':'muted')+'">'+h(d?.facts[k]||'Not captured')+'</strong></button>').join('')+'</section><section class="support-card support-offer"><div class="between"><h3>Offer at a glance</h3>'+jump('Open','offers')+'</div><p>'+h(q?q.lines.map(l=>l.name).join(' + '):'No offer saved yet')+'</p><div class="mini-row"><span>Initial quote</span><b>'+C.money(C.quoteTotal(q))+'</b></div><div class="mini-row"><span>Net collected</span><b>'+C.money(net)+'</b></div><div class="compact-milestones">'+[['Agreed',d?.acceptedAt],['Authorized',d?.authorizedAt],['Paid',net>0]].map(([t,done])=>'<span class="'+(done?'done':'')+'">'+icon(done?'check':'clock')+t+'</span>').join('')+'</div></section><section class="support-card"><div class="between"><h3>Next commitment</h3>'+jump('Open','follow')+'</div><p>'+h(d?.task&&!d.task.done?d.task.purpose:'No next event set')+'</p>'+(d?.task&&!d.task.done?'<small>'+h(stamp(d.task.at))+'</small>':'')+'</section>';
 }
 function suggestedSection(a){return {permission:'open',evidence:'discovery',coverage:'account',offer:'offers',objection:'objections',decision:'discovery',accept:'close',authorize:'payment',payment:'payment',activate:'activate',covered:'account',closed:'recap',refunded:'payment',complete:'recap'}[a.kind]||'discovery';}
 function searchResults(query){
  const q=query.trim().toLowerCase();
  const items=[...sections.map(s=>({title:s.title,detail:s.group,keywords:s.keywords,action:'desk-jump',extra:'data-section="'+s.id+'"',icon:s.icon})),{title:'New customer',detail:'ACTION',keywords:'new deal account',action:'new-deal',extra:'',icon:'plus'},{title:'Working notes',detail:'ACTION',keywords:'capture write',action:'notes',extra:'',icon:'edit'},{title:'Copy Salesforce recap',detail:'ACTION',keywords:'crm copy',action:'copy-recap',extra:'',icon:'copy'},{title:'Set a follow-up',detail:'ACTION',keywords:'callback next event schedule',action:'task',extra:'',icon:'clock'}].filter(x=>!q||[x.title,x.detail,x.keywords].join(' ').toLowerCase().includes(q));
  return items.length?items.map(x=>'<button class="jump-result" data-action="'+x.action+'" '+x.extra+'>'+icon(x.icon)+'<span><b>'+h(x.title)+'</b><small>'+h(x.detail)+'</small></span>'+icon('arrow')+'</button>').join(''):'<p class="no-results">No matching section. Try “tax,” “payment,” or “notes.”</p>';
 }
 return {render,support,searchResults,sections};
}
root.RevDeskOpenDesk={create,sections};
})(typeof window!=='undefined'?window:globalThis);
